name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/${{ vars.IMAGE_NAMESPACE }}/${{ vars.IMAGE_NAME }}latest
            docker.io/${{ vars.IMAGE_NAMESPACE }}/${{ vars.IMAGE_NAME }}:${{ github.ref_name }}
          build-args: |
            TZ=${{ vars.TZ }}
            USE_ALIYUN_MIRROR=${{ vars.USE_ALIYUN_MIRROR }}
            GOPROXY=${{ vars.GOPROXY }}
